version: "3.9"
services:
    mysql:
        image: mysql:8.0.31
        container_name: cp-db
        working_dir: /var/www/html
        command: --default-authentication-plugin=caching_sha2_password
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            PMA_HOST: mysql
        ports:
            - "${CUSTOM_DB_PORT:-3306}:3306"
        restart: unless-stopped

    mysql-testing:
        image: mysql:8.0.31
        working_dir: /var/www/html
        command: --default-authentication-plugin=caching_sha2_password
        container_name: cp-db-testing
        environment:
            MYSQL_DATABASE: ${TESTING_DB_DATABASE}
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: ${TESTING_DB_PASSWORD}
            MYSQL_PASSWORD: ${TESTING_DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            PMA_HOST: mysql-testing
        volumes:
            - mysql-testing:/var/lib/mysql
        ports:
            - "${CUSTOM_TESTING_DB_PORT:-3307}:3306"
        restart: unless-stopped

    nginx:
        image: nginx:stable-alpine
        container_name: cp-nginx
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${CUSTOM_NGINX_PORT:-80}:80"
        depends_on:
            - php
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        container_name: cp-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-ext-overrides.ini
        depends_on:
            - mysql
            - mysql-testing
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    default:

volumes:
    mysql:
    mysql-testing:
